### ISSUE TITLE
Geometry generated with holes

### ISSUE THREAD

**Issue by mkapolka** [sabresaurus/SabreCSG#163] opened 2018-08-07 01:43 UTC
@Henry00IS reached out on twitter when I was complaining about geometry being generated with holes. Here's one of the cases that I've always had trouble with: Subtracting a cylinder from another cylinder. 

I'm running Unity 2018.2.1f1 on OSX High Sierra (10.13.6) and the `master` branch pulled just before making this example. Attached is an image of the bug and a project containing the geometry.

![screen shot 2018-08-06 at 6 40 51 pm](https://user-images.githubusercontent.com/3412796/43749278-47918070-99a8-11e8-942f-c26e3e9a07fd.png)

[hollowed_cylinder_package.unitypackage.zip](https://github.com/sabresaurus/SabreCSG/files/2264626/hollowed_cylinder_package.unitypackage.zip)

**Comment by Henry00IS** [comment] 2018-08-14 06:47
Subtracting a cylinder from another cylinder has already been known to be a problem since #8. It was significantly worse in previous versions though (see #138).

Floating point inaccuracy makes it very difficult to classify whether a polygon is inside or outside of another brush for example, as the rounding errors get exceedingly worse the further you move away from 0,0,0 world space. Any math functions you rely on like trigonometry start to turn into a rounded blur meaning we have approximate checks, if an operation is "more or less" equal we assume it's probably correct. Too many assumptions to deal with the inaccuracy is causing false positives, surfaces that shouldn't be removed get removed and new surfaces that don't even exist get introduced (usually always inside of the walls, a certain "onion skin", but still not nice). Round and rotated brushes suffer the most, hence why this type of cylinder operation is likely to break, some wiggling around tends to fix it.

We have been discussing using fixed-point maths for a long time now and it's again a topic in Discord. It would deal with this issue (and likely all other corruptions caused by floating point precision errors). I am looking forward to implementing such a thing soon with the community.

**Comment by Henry00IS** [comment] 2018-11-05 13:34
This is technically a duplicate of #8 and to keep things organized I will close this issue.

**Closed by Henry00IS** 2018-11-05 13:34 UTC
Labels: type: duplicate, type: sabresaurus
