### ISSUE TITLE
Clicking on a face, make it´s texture distorted and shows the error

### ISSUE THREAD

**Issue by rickomax** [sabresaurus/SabreCSG#7] opened 2017-04-03 01:26 UTC
Clicking on a face, make it´s texture distorted and shows the error:

IndexOutOfRangeException: Array index is out of range.
Sabresaurus.SabreCSG.SurfaceEditor.TransformUVs (Sabresaurus.SabreCSG.Polygon polygon, Sabresaurus.SabreCSG.UVTransformation transformationMethod, Sabresaurus.SabreCSG.TransformData transformData, Boolean recordUndo) (at Assets/SabreCSG-master/Scripts/Tools/SurfaceEditor.cs:1037)
Sabresaurus.SabreCSG.SurfaceEditor.TransformUVs (Sabresaurus.SabreCSG.UVTransformation transformationMethod, Sabresaurus.SabreCSG.TransformData transformData, Boolean recordUndo) (at Assets/SabreCSG-master/Scripts/Tools/SurfaceEditor.cs:985)
Sabresaurus.SabreCSG.SurfaceEditor.OnMouseDragTranslate (UnityEditor.SceneView sceneView, UnityEngine.Event e) (at Assets/SabreCSG-master/Scripts/Tools/SurfaceEditor.cs:391)
Sabresaurus.SabreCSG.SurfaceEditor.OnMouseDrag (UnityEditor.SceneView sceneView, UnityEngine.Event e) (at Assets/SabreCSG-master/Scripts/Tools/SurfaceEditor.cs:280)
Sabresaurus.SabreCSG.SurfaceEditor.OnSceneGUI (UnityEditor.SceneView sceneView, UnityEngine.Event e) (at Assets/SabreCSG-master/Scripts/Tools/SurfaceEditor.cs:108)
Sabresaurus.SabreCSG.CSGModel.OnSceneGUI (UnityEditor.SceneView sceneView) (at Assets/SabreCSG-master/Scripts/CSGModel.cs:506)
UnityEditor.SceneView.CallOnSceneGUI () (at C:/buildslave/unity/build/Editor/Mono/SceneView/SceneView.cs:2075)
UnityEditor.SceneView.HandleSelectionAndOnSceneGUI () (at C:/buildslave/unity/build/Editor/Mono/SceneView/SceneView.cs:1405)
UnityEditor.SceneView.OnGUI () (at C:/buildslave/unity/build/Editor/Mono/SceneView/SceneView.cs:1242)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)

![saber](https://cloud.githubusercontent.com/assets/12863984/24592879/9fcea50c-17f3-11e7-97a7-337a2f389375.png)

**Comment by Henry00IS** [comment] 2018-03-20 11:24
Rickomax, if you are still here, did you ever find the reason why it happened and how to fix this?

This issue is nearly a year old and I have never encountered this error before. If anyone is able to reproduce it and detail the steps or provide a link to a scene with this problem it's very much appreciated.

Worst case we will have to close this issue and hope that one day someone encounters it again (or not, as that would be a bad thing).

**Comment by rickomax** [comment] 2018-03-22 15:08
Hi @Henry00IS . I haven't used SabreCSG anymore...

**Comment by Henry00IS** [comment] 2018-03-23 13:51
Thanks @rickomax for taking the time to write a reply. That's too bad, I hope you will check it out again sometime, there are many new features and improvements.

I will close this issue until anyone ever encounters it again and finds a way to reproduce the error. For all I know the underlying cause may have already been fixed over time.

**Closed by Henry00IS** 2018-03-23 13:51 UTC
Labels: status: cannot-reproduce, type: bug
