### ISSUE TITLE
Curved stairs / walls not resizing

### ISSUE THREAD

**Issue by Constaneer** [sabresaurus/SabreCSG#108] opened 2018-05-08 10:47 UTC
I'm not sure if this is meant to be a bug or a feature, but when resizing the curved stair / wall on the x and z axis, it doesn't do anything, but when you resize on the y axis it adds more faces to the brush, it also resizes on the y axis. 
Example - https://youtu.be/GEpLqSwHbwg

**Comment by Henry00IS** [comment] 2018-05-08 11:25
Yeah it's a "feature", a deliberate design choice. In the beginning it was impossible to resize any axis and then the Sabresaurus insisted that I at least make it possible to add steps by resizing. The problem is the bounding box changes rapidly depending on your configuration and for some changes it may not change at all because it fits in the same bounding box: [https://twitter.com/twitter/statuses/955874461240250369](https://twitter.com/twitter/statuses/955874461240250369)

So it's really difficult if not impossible to use the ordinary bounds tools. I generate the bounding box every time you change the configuration of the stairs. The same thing happens with all 2DSE brushes, you can't change the bounding box at all there for similar reasons.

**Comment by Henry00IS** [comment] 2018-05-08 17:18
I'm closing this issue for now. Perhaps one day we will have actual interactive tools for this sort of thing. But thank you for taking the time to open an issue. It's nice to see someone using SabreCSG, especially when it's one of the things I made. 😁

**Closed by Henry00IS** 2018-05-08 17:18 UTC
Labels: type: wontfix
